language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew mobile:check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
