language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26

before_install:
  - chmod +x gradlew

script:
  - ./gradlew mobile:check

notifications:
  emails: false
